### ISSUE TITLE
Use today date while adding a scheduled transaction in the future

### ISSUE THREAD

**Issue by Romamo** [bkper/exchange-bot#28]
Adding a scheduled transaction in the future results in the error "Historical rates for the requested date are not available - please try another date or contact support@openexchangerates.org"

Because of this issue, paired transactions are not created.

Please use today date instead date in the future.

The rates will be adjusted automatically when the transaction is marked as "Checked".

**Comment by maelcaldas** [comment]
That makes sense. Thanks for reporting it.

We just released it. See [commit](https://github.com/bkper/exchange-bot/compare/e7c50a1b6e57...bdfd3730769f)
